### ISSUE TITLE
other adaption algorithm

### ISSUE THREAD

**Issue by leslie-wang** [ldecicco/tapas#2]
besides PANDA, is there any plan to create other algorithms? such Miller's http://www.tkn.tu-berlin.de/fileadmin/fg112/Papers/Adaptation_Algorithm_for_Adaptive_Streaming_over_HTTP.pdf?

**Comment by pckbls** [comment]
Hi there,

I've recently written my bachelor thesis at TU Berlin with Miller being my supervisor. As part of my work I had to implement his adaptation strategy for TAPAS. You can find the source code [here](https://gitlab.tubit.tu-berlin.de/petz1337/tapas-tkn).

I definately should create a pull request though.

Cheers
Patrick

**Comment by leslie-wang** [comment]
Thanks for reply. It is super cool! Please kindly merge here. hope we can see more controllers. One paper compares 10 different controller algorithms. It would be great if all these controllers can be implemented here, then any people can do fair comparison using one framework.

I'll create separate issues for each controller in this paper.

Quality of Experience of Adaptive HTTP Streaming in Real-World Environments http://www-itec.uni-klu.ac.at/bib/files/QoE-DASH.pdf

**Comment by ldecicco** [comment]
Hi guys,

thanks for using and hacking TAPAS. @pckbls  if you want your code to be added to the official version of TAPAS please file a merge request. 

I am open to add any other controllers. Please keep them coming :)
